# Generated by Django 4.2.6 on 2023-10-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="cart price",
                    ),
                ),
                (
                    "is_ordered",
                    models.BooleanField(default=False, verbose_name="is ordered"),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="date added"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date added"),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
                "ordering": ["date_added"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
            ],
            options={
                "verbose_name": "cart item",
                "verbose_name_plural": "carts items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Created", "Created"), ("Ordered", "Ordered")],
                        default="Created",
                        max_length=120,
                        verbose_name="status",
                    ),
                ),
                (
                    "total_order_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=100,
                        verbose_name="total order price",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.cart",
                        verbose_name="cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-timestamp"],
            },
        ),
    ]
