# Generated by Django 4.2.6 on 2023-12-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_option",
            field=models.CharField(
                choices=[("cash", "cash"), ("card terminal", "card terminal")],
                default="Cash",
                max_length=120,
                verbose_name="payment option",
            ),
        ),
    ]
