# Generated by Django 4.2.6 on 2023-10-06 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="name (Turkmen)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="name (English)"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="name (Russian)"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description (Turkmen)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="description (English)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="description (Russian)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/categories/", verbose_name="image"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="type (Turkmen)",
                    ),
                ),
                (
                    "type_en",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="type (English)",
                    ),
                ),
                (
                    "type_ru",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="type (Russian)",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="model (Turkmen)"
                    ),
                ),
                (
                    "model_en",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="model (English)"
                    ),
                ),
                (
                    "model_ru",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="model (Russian)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="title (Turkmen)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="title (English)"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="title (Russian)"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description (Turkmen)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="description (English)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="description (Russian)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="title (Turkmen)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="title (English)"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="title (Russian)"
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=255, verbose_name="content (Turkmen)"),
                ),
                (
                    "content_en",
                    models.CharField(max_length=255, verbose_name="content (English)"),
                ),
                (
                    "content_ru",
                    models.CharField(max_length=255, verbose_name="content (Russian)"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="products.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product spec",
                "verbose_name_plural": "product specs",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/products/", verbose_name="image"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="description"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
    ]
