# Generated by Django 4.2.6 on 2023-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="name (Turkmen)"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="name (English)"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="name (Russian)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False, verbose_name="on sale"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=6, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="type (Turkmen)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_en",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="type (English)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_ru",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="type (Russian)",
            ),
        ),
    ]
