# Generated by Django 4.2.6 on 2023-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                upload_to="images/categories/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="images/products/", verbose_name="image"),
        ),
    ]
