# Generated by Django 4.2.6 on 2023-12-28 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_name_alter_category_name_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["created_at"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
