# Generated by Django 4.2.6 on 2024-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                max_length=50, null=True, verbose_name="type (Turkmen)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="type (English)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_ru",
            field=models.CharField(
                max_length=50, null=True, verbose_name="type (Russian)"
            ),
        ),
    ]
