# Generated by Django 4.2.6 on 2024-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_price_alter_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="type (Turkmen)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_en",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="type (English)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_ru",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="type (Russian)",
            ),
        ),
    ]
